# data.py

dat_1 = [
    ("various", "형. 여러 가지의, 각양 각색의"),
    ("shift", "동. 옮기다, 이동하다 / 명. 교대 근무(시간), 교대조"),
    ("facility", "명. 시설[기관]"),
    ("revise", "동. 변경[수정]하다, 개정하다"),
    ("flexible", "형. 신축성[융통성] 있는, 유연한"),
    ("leak", "동. 새다 / 명. 새는 곳, 틈"),
    ("within", "전. (특정한 기간, 거리) 이내에[안에]"),
    ("refurbish", "동. 새로 꾸미다, 재단장하다"),
    ("representative", "명. 대표(자), 대리인 / 형. 대표하는"),
    ("notice", "동. 주목하다, 관심을 기울이다 / 명. 주목, 알아챔, 공고문"),
    ("distinguished", "형. 유명한, 성공한, 기품 있는"),
    ("resident", "명. 거주자, 주민"),
    ("apprentice", "명. 수습생, 도제 / 동. 수습생으로 삼다"),
    ("significant", "형. 중요한, 의미 있는"),
    ("punctual", "형. 시간을 지키는, 엄수하는"),
    ("consecutive", "형. 연이은, 연속적인"),
    ("merger", "명. 합병"),
    ("terminate", "동. 끝나다, 종료되다, 종점에 닿다"),
    ("laboratory", "명. 실험실"),
    ("blueprint", "명. 청사진, 계획"),
    ("innovative", "형. 획기적인, 혁신적인"),
    ("prop", "명. 지주, 버팀목, 받침대 / 동. (받침대 등으로) 받치다"),
    ("duplicate", "동. 복사[복제]하다, 사본을 만들다 / 형. 똑같은, 꼭 닮은, 사본의"),
    ("verify", "동. 확인하다, 입증하다"),
    ("ensure", "동. 보장하다, 반드시 ~하게 하다"),
    # 숙어 및 관용 표현 (5개)
    ("place an order", "주문하다"),
    ("address problems, issues", "문제를 해결하다"),
    ("meet a deadline", "마감기한을 맞추다"),
    ("be known for (이유)", "~로 알려져 있다"),
    ("take measures", "조치를 취하다, 대책을 강구하다"),
]

dat_2 = [
    ("hesitate", "동. 망설이다, 주저하다"),
    ("attach", "동. 붙이다, 첨부하다"),
    ("applause", "명. 박수, 갈채"),
    ("issue", "명. 주제, 쟁점, 문제, 호, 발행 / 동. 발부[발행]하다, 발표[공표]하다"),
    ("domestic", "형. 국내의, 가정(용)의"),
    ("acquaintance", "명. 지인, 친분, 지식"),
    ("inclement weather", "phr. 나쁜 날씨, 악천후"),
    ("renowned", "형. 유명한, 명성 있는"),
    ("fragile", "형. 부서지기 쉬운, 취약한"),
    ("versatile", "형. 다재다능한, 다용도의"),
    ("disregard", "동. 무시[묵살]하다 / 명. 무시, 묵살"),
    ("relinquish", "동. 포기하다, 내주다"),
    ("thrive", "동. 번창하다"),
    ("bankrupt", "형. 파산한 / 명. 파산자, 파산 선고를 받은 사람"),
    ("comply", "동. 따르다, 준수하다"),
    ("readership", "명. 독자 수[층]"),
    ("decade", "명. 10년"),
    ("occasion", "명. 때, 기회. 경우 / 동. ~의 원인이 되다"),
    ("occupation", "명. 직업, 사용, 거주"),
    ("delegate", "명. 대표(자) / 동. 위임하다"),
    ("correspondence", "명. 서신, 편지"),
    ("entrepreneur", "명. 사업가, 기업가"),
    ("minutes", "명. 회의록"),
    ("shortage", "명. 부족"),
    ("flourish", "동. 번창하다(=thrive) / 명. 과장된 동작"),
    # 숙어 및 관용 표현 (5개)
    ("take advantage of", "~을 이용하다, ~을 기회로 활용하다"),
    ("make sure that", "that이하를 확실하게 하다"),
    ("be based in", "~에 기반을 두다"),
    ("give details about", "~에 대해 상세히 설명하다"),
    ("be required to do", "~하도록 요구되다"),
]

dat_3 = [
    ("durable", "형. 내구성이 좋은, 오래가는"),
    ("nomination", "명. 지명, 추천, 임명"),
    ("steady", "형. 꾸준한 / 동. 균형을 잡다, 흔들리지 않다"),
    ("leading", "형. 가장 중요한, 선도하는"),
    ("qualified", "형. 자격이 있는"),
    ("imperative", "형. 반드시 해야 하는, 긴요한"),
    ("outreach", "명. 봉사[원조, 지원] 활동"),
    ("assemble", "동. 모이다, 집합시키다, 조립하다"),
    ("endorse", "동. 지지하다, 보증[홍보]하다"),
    ("disclose", "동. 밝히다, 폭로하다, 드러내다"),
    ("commemorate", "동. (중요 인물 사건을) 기념하다"),
    ("terminate", "동. 끝나다, 종점에 달하다"),
    ("account", "명. 계좌, 장부, 계정, 설명 / 동. 설명하다(for), 차지하다(for)"),
    ("extension", "명. 확대, 증축(된) 건물"),
    ("congestion", "명. 혼잡"),
    ("substantially", "부. 상당히, 많이"),
    ("mainly", "부. 주로, 대부분, 대개"),
    ("accurate", "형. 정확한, 정밀한"),
    ("complete", "형. 완벽한, 완전한 / 동. 완료하다, 끝마치다, 기입하다"),
    ("separate", "형. 분리된, 독립된 / 동. 분리하다, 갈라지다"),
    ("patron", "명. 후원자, 고객"),
    ("testimonial", "명. 추천서, 추천의 글"),
    ("extend", "동. 더 길게 만들다, 연장하다"),
    ("power outage", "명. 정전"),
    ("avid", "형. 열심인, 열렬한, 열망하는"),
    # 숙어 및 관용 표현 (5개)
    ("make a mistake", "실수하다, 잘못 생각하다"),
    ("respond to", "~에 응답, 대응하다"),
    ("conveniently located", "편리한 위치에 있는"),
    ("highly regard", "~을 중시하다"),
    ("on duty", "근무 중"),
]

dat_4 = [
    ("culinary", "형. 요리의, 음식의"),
    ("sweep", "동. 쓸다, 청소하다"),
    ("pedestrian", "명. 보행자"),
    ("dig", "동. 파다, 파내다, 캐다"),
    ("pavement", "명. 인도, 보도, 포장면"),
    ("alternative", "명. 대안, 선택 가능한 것 / 형. 대체 가능한, 대안이 되는"),
    ("beverage", "명. 음료"),
    ("refreshment", "명. 다과, 가벼운 식사"),
    ("accelerate", "동. 가속화되다, 가속화하다"),
    ("through", "전. ~을 통해, 지나[거쳐, 통과하여] / 부. 통과하여"),
    ("mention", "동. 언급하다, 말하다 / 명. 언급[거론]"),
    ("year-end", "명. 연말 / 형. 연말의"),
    ("appointment", "명. 약속, 임명, 지명"),
    ("misplace", "동. 제자리에 두지 않다"),
    ("schedule conflict", "명. 일정 충돌"),
    ("accommodation", "명. 거처, 숙소, 시설"),
    ("demonstration", "명. 시위, 데모, 시연"),
    ("regard", "동. ~을 …으로 여기다 / 명. 관심, 존경"),
    ("highly", "부. 크게, 대단히, 매우"),
    ("promptly", "부. 지체 없이, 즉시"),
    ("mow", "동. 깎다, 베다"),
    ("exhibition", "명. 전시회, 전시"),
    ("branch", "명. 지사, 분점"),
    ("flagship store", "명. 본점, 주력 상점"),
    ("win", "동. 이기다, 따다[쟁취하다]"),
    # 숙어 및 관용 표현 (5개)
    ("in bulk", "대량으로"),
    ("in accordance with", "~에 따라서, ~에 부합되게"),
    ("adhere to", "~을 고수하다, 지키다"),
    ("reserve the right to do", "~할 권리가 있다"),
    ("come up with", "제시[제안]하다, 떠올리다"),
]

dat_5 = [
    ("retirement", "명. 은퇴, 퇴직"),
    ("inaugurate", "동. 취임하게 하다"),
    ("probation", "명. 보호 관찰, 수습(기간)"),
    ("consequently", "부. 그 결과, 따라서"),
    ("relocate", "동. 이전[이동]하다[시키다]"),
    ("replacement", "명. 교체, 대체, 후임자"),
    ("broaden", "동. 넓어지다, 퍼지다"),
    ("immediately", "부. 즉시, 즉각, 곧바로"),
    ("appraise", "동. 살피다, (업무를) 평가하다"),
    ("enforce", "동. 강요하다, (법률 등을) 집행하다"),
    ("abruptly", "부. 갑자기, 불쑥, 뜻밖에"),
    ("severe", "형. 극심한, 심각한"),
    ("mutually", "부. 서로, 상호간에"),
    ("implement", "동. 시행하다 / 명. 도구, 기구"),
    ("sanitize", "동. 위생 처리하다, 살균하다"),
    ("cease", "동. 중단되다, 그치다, 중단시키다"),
    ("evaluate", "동. 평가하다, 감정하다"),
    ("monthly", "형. 한 달에 한 번의 / 부. 매월, 다달이"),
    ("attainable", "형. 이룰 수 있는, 달성할 수 있는"),
    ("currency", "명. 통화"),
    ("interest rate", "명. 금리, 이율"),
    ("in advance", "phr. 미리"),
    ("apparently", "부. 듣자 하니, 보아 하니"),
    ("tend", "동. 경향이 있다, 돌보다, 보살피다"),
    ("modification", "명. 수정, 변경"),
    # 숙어 및 관용 표현 (5개)
    ("take measures", "조치를 취하다, 대책을 강구하다"),
    ("conduct a survey", "설문조사를 하다"),
    ("be responsible for", "~에 책임이 있다"),
    ("reach an agreement", "합의에 도달하다"),
    ("refrain from", "~을 삼가다"),
]

dat_6 = [
    ("procedure", "명. 절차, 방법"),
    ("capacity", "명. 용량, 수용력"),
    ("lightweight", "형. 가벼운 / 명. 라이트급 선수"),
    ("eventually", "부. 결국, 종내"),
    ("complex", "형. 복잡한 / 명. 복합 건물"),
    ("timely", "형. 시기적절한, 때맞춘"),
    ("stringent", "형. 엄중한, 긴박한, 절박한"),
    ("emphasis", "명. 강조"),
    ("operation", "명. 수술, 작전, 기업"),
    ("available", "형. 구할 수 있는, 이용할 수 있는"),
    ("factor", "명. 요소, 요인"),
    ("feasible", "형. 실현 가능한"),
    ("impeccable", "형. 흠 잡을 데 없는"),
    ("redeemable", "형. (현금 상품과) 교환할 수 있는"),
    ("findings", "명. 조사 결과물"),
    ("garment", "명. 의복, 옷"),
    ("property", "명. 재산, 소유물, 부동산"),
    ("catering", "명. 음식 공급, 출장뷔페업체 서비스"),
    ("conglomerate", "명. 복합 기업, 대기업"),
    ("vendor", "명. 상인"),
    ("doubt", "명. 의심, 의문 / 동. 의심하다, 확신하지 못하다"),
    ("malicious", "형. 악의적인, 적의 있는"),
    ("complimentary", "형. 무료의, 칭찬하는"),
    ("inquiry", "명. 질문, 문의, 연구, 탐구"),
    ("deliberation", "명. 숙고, 신중함"),
    # 숙어 및 관용 표현 (5개)
    ("put off", "연기하다, 미루다"),
    ("look for", "찾다"),
    ("volunteer for", "에 지원하다"),
    ("be willing to do", "기꺼이 ~ 하다, 흔쾌히 ~하다"),
    ("file a complaint", "항의를 제기하다"),
]

dat_7 = [
    ("willing", "형. 기꺼이 하는, 자발적인, 꺼리지 않는"),
    ("noteworthy", "형. 주목할 만한"),
    ("supplementary", "형. 보충의, 추가의"),
    ("dispute", "명. 분쟁, 분규, 논란 / 동. 반박하다, 이의를 제기하다"),
    ("eager", "형. 열렬한, 간절히 바라는, 열심인"),
    ("utility fee", "phr. 공공요금"),
    ("venue", "명. 장소"),
    ("undergo", "동. (변화나 안 좋은 일 등을) 겪다"),
    ("specialize", "동. ~을 전공하다, 전문적으로 하다"),
    ("compile", "동. 엮다, 편집[편찬]하다"),
    ("apron", "명. 앞치마"),
    ("conventional", "형. 관습적인, 관례적인"),
    ("robust", "형. 원기 왕성한, 팔팔한, 튼튼한, 강력한"),
    ("secondhand", "형. 간접의, 중고의"),
    ("cautious", "형. 조심스러운, 신중한"),
    ("crack", "동. 갈라지다, 금이 가다, 깨지다 / 명. 금, 틈"),
    ("tremendous", "형. 엄청난, 굉장한, 대단한"),
    ("simplify", "동. 간소화하다, 단순화하다"),
    ("double-book", "동 이중으로 예약을 받다"),
    ("remote control", "명. 원격 조종, 리모콘"),
    ("breach", "명. 위반 / 동. 위반하다, 어기다"),
    ("portable", "형. 휴대가 쉬운, 휴대용의 / 명. 휴대용 제품"),
    ("seasoned", "형. 경험 많은, 노련한, 양념을 한"),
    ("receipt", "명. 영수증, 수령"),
    ("fountain", "명. 분수"),
    # 숙어 및 관용 표현 (5개)
    ("at a reasonable price", "합당한 가격으로"),
    ("come with", "~이 딸려 있다"),
    ("out of order", "고장난"),
    ("be vulnerable to", "~에 영향을 받기 쉽다, 취약하다"),
    ("in light of", "~을 고려하여, ~에 비추어"),
]

dat_8 = [
    ("tidy", "형. 깔끔한, 잘 정돈된 / 동. 정돈하다, 정리하다"),
    ("flyer", "명. 전단지(print -), 비행기 승객"),
    ("slightly", "부. 약간, 조금"),
    ("excursion", "명. 여행, 외도"),
    ("lodging", "명. 임시 숙소, 하숙"),
    ("gifted", "형. 재능이 있는"),
    ("transparent", "형. 투명한, 명백한"),
    ("sheer", "형. 순전한, 순수한"),
    ("thoroughly", "부. 대단히, 완전히, 철저히"),
    ("unanimously", "부. 만장일치로"),
    ("meticulous", "형. 꼼꼼한, 세심한"),
    ("itinerary", "명. 여행 일정표"),
    ("keen", "형. 간절히 하고 싶은, 열망하는"),
    ("cast", "동. (그림자를) 드리우다 / 명. (연극이나 영화의) 출연자들"),
    ("voucher", "명. 상품권, 할인권, 쿠폰"),
    ("expenditure", "명. 지출, 비용, 경비"),
    ("reimbursement", "명. 상환, 변제"),
    ("remnant", "명. 남은 부분, 나머지"),
    ("collaborate", "동. 협력하다, 공동으로 작업하다"),
    ("wing", "명. 날개, 부속 건물, 동 / 동. 날아가다, 신속히 보내지다"),
    ("alert", "형. 기민한, 경계하는 / 동. 알리다, 경보를 발하다"),
    ("relevant", "형. 관련 있는, 적절한"),
    ("decline", "명. 감소, 하락, 축소 / 동. 줄어들다, 감소하다, 거절하다"),
    ("excavation", "명. 발굴, 발굴지"),
    ("urgent", "형. 긴급한, 시급한"),
    # 숙어 및 관용 표현 (5개)
    ("on behalf of", "~을 대신하여, ~을 대표하여"),
    ("make up for", "(손실 따위를) 보상하다, 보전하다"),
    ("go over", "조사하다, 검토하다"),
    ("participate in", "~에 참가하다, 참여하다"),
    ("take into account", "~을 고려하다"),
]

dat_9 = [
    ("genuine", "형. 진짜의, 진품의"),
    ("inevitable", "형. 불가피한, 필연적인"),
    ("postpone", "동. 연기하다, 미루다"),
    ("ingredient", "명. 재료, 성분"),
    ("vessel", "명. 선박, 배, 그릇, 용기, (동물의) 혈관"),
    ("budget", "명. 예산, 비용 / 동. 예산을 세우다"),
    ("vacant", "형. 비어 있는, 사람이 없는, 결원의"),
    ("dense", "형. 빽빽한, 밀집한, 짙은"),
    ("notable", "형. 주목할 만한, 눈에 띄는"),
    ("roughly", "부. 대략, 거의, 거칠게"),
    ("emerging", "형. 최근 생겨난, 최근에 만들어진"),
    ("demolish", "동. (건물을) 철거하다, (사상이나 이론을) 뒤집다"),
    ("intimate", "형. 친밀한, 사적인"),
    ("workload", "명. 업무량, 작업량"),
    ("last-minute", "형. 마지막 순간의, 막바지의"),
    ("fundamental", "형. 근본적인, 핵심적인 / 명. 기본 원칙, 핵심"),
    ("considerate", "형. 사려 깊은, 배려하는"),
    ("hospitality", "명. 환대, 후대"),
    ("destination", "명. 목적지, 도착지"),
    ("withdraw", "동. 철수하다, (계좌에서 돈을) 인출하다"),
    ("in person", "phr. 직접, 몸소"),
    ("route", "명. 길, 경로, 노선 / 동. (특정 루트를 따라)보내다, 전송하다"),
    ("detour", "명. 우회로 / 동. 둘러 가다, 우회하다"),
    ("demand", "명. 요구 사항 / 동. 요구하다, 필요로 하다"),
    ("secure", "형. 안심하는, 안전한 / 동. 획득[확보]하다, 고정시키다"),
    # 숙어 및 관용 표현 (5개)
    ("replace A with B", "A를 B로 치환하다"),
    ("let A know B", "A에게 B를 알게 하다"),
    ("unless otherwise noted", "달리 언급이 없으면"),
    ("as for", "~에 관해 말하면"),
    ("run behind schedule", "일정에 뒤처지다"),
]

dat_10 = [
    ("advanced", "형. 선진의, 고급의"),
    ("permanent", "형. 영구적인, 영속적인"),
    ("original", "형. 원래의, 본래의, 독창적인 / 명. 원본"),
    ("intricate", "형. 복잡한"),
    ("obsolete", "형. 더 이상 쓸모가 없는, 한물간, 구식의"),
    ("state-of-the-art", "형. 최첨단의, 최신식의"),
    ("stunning", "형. 굉장히 아름다운[멋진], 깜짝 놀랄"),
    ("profound", "형. 엄청난, 깊은, 심오한"),
    ("rubbish", "명. 쓰레기"),
    ("dwindle", "동. 줄어들다"),
    ("appeal", "명. 항소, 매력 / 동. 항고하다, 관심을 끌다, 매력적이다"),
    ("vertical", "형. 수직의, 세로의 / 명. 수직(선면)"),
    ("horizon", "명. 수평선, 지평선, 시야, 전망"),
    ("ergonomic", "형. 인체 공학의"),
    ("keynote", "명. (책이나 연설 등의) 주안점[기조]"),
    ("resign", "동. 사직하다, 물러나다"),
    ("refrain", "동. 삼가다"),
    ("reflect", "동. (상을) 비추다, 반사하다, 반영하다"),
    ("deteriorate", "동. 악화되다, 더 나빠지다"),
    ("rigorous", "형. 철저한, 엄격한"),
    ("diploma", "명. 졸업장, 수료증"),
    ("qualification", "명. 자격[자격증], 자질, 능력"),
    ("pharmacy", "명. 약국, 조제실"),
    ("outskirt", "명. 변두리, 교외, 한계, 빠듯함"),
    ("waive", "동. (권리 등을) 포기하다"),
    # 숙어 및 관용 표현 (5개)
    ("within walking distance", "도보로 갈 수 있는 거리 이내에"),
    ("under construction", "공사 중인, 건설 중인"),
    ("on time", "정각에, 시간을 어기지 않고"),
    ("newly hired", "신규로 채용된"),
    ("thoroughly examine", "면밀하게 검사하다"),
]

dat_11 = [
    ("throughout", "전. 도처에, 쭉, 내내"),
    ("quickly", "부. 빨리, 빠르게"),
    ("publicize", "동. 알리다, 광고[홍보]하다"),
    ("affect", "동. 영향을 미치다"),
    ("party", "명. 정당, 단체 / 동. 파티하다"),
    ("initial", "형. 처음의, 초기의 / 명. 첫 글자"),
    ("guarantee", "명. 품질 보증서 / 동. 보장하다, 품질 보증을 하다"),
    ("pharmaceutical", "형. 제약의, 약학의 / 명. 약, 제약"),
    ("medicine", "명. 의학, 의술, 약, 약물"),
    ("investigate", "동. 조사하다"),
    ("reasonably", "부. 상당히, 꽤, 합리적으로"),
    ("portion", "명. 부분, 일부, 1인분"),
    ("bid", "동. 값을 부르다, 입찰에 응하다 / 명. 가격 제시, 호가, 응찰"),
    ("forbid", "동. 금지하다"),
    ("struggle", "동. 투쟁하다, 몸부림치다 / 명. 투쟁, 분투"),
    ("scented", "형. 강한 향기가 나는, 향기로운"),
    ("assistant", "명. 조수, 보조원"),
    ("troubleshooting", "명. 고장의 수리"),
    ("exceed", "동. 넘다, 초과하다, 초월하다"),
    ("via", "전. 통하여"),
    ("ownership", "명. 소유(권)"),
    ("indefinitely", "부. 무기한으로"),
    ("absolute", "형. 완전한, 완벽한 / 명. 절대적인 것"),
    ("complicated", "형. 복잡한"),
    ("distinctive", "형. 독특한"),
    # 숙어 및 관용 표현 (5개)
    ("temporarily out of stock", "일시적 재고 품절"),
    ("cope with", "~에 대처하다, 대응하다"),
    ("stop by", "가는 길에 들르다"),
    ("concentrate on", "~에 집중하다"),
    ("mutually benificial", "상호 이익이 되는"),
]

dat_12 = [
    ("chronic", "형. 만성적인, 만성 질환을 앓고 있는"),
    ("accountant", "명. 회계사"),
    ("shortlist", "명. 최종 후보자 명단"),
    ("heritage", "명. 유산"),
    ("fuel", "명. 연료 / 동 연료를 공급하다, 기름을 넣다"),
    ("renewable", "형. 재생 가능한"),
    ("customized", "형. 개개인의 요구에 맞춘"),
    ("ongoing", "형. 계속 진행 중인"),
    ("rare", "형. 드문, 희귀한, 진귀한"),
    ("resume", "동. 재개하다, 다시 시작하다"),
    ("allegation", "명. 혐의, 주장"),
    ("inclination", "명. 의향, 성향"),
    ("persistence", "명. 고집, 지속됨"),
    ("valid", "형. 유효한, 정당한, 타당한"),
    ("safety gear", "명. 안전 장치"),
    ("forklift", "명. 지게차"),
    ("criteria", "명. 표준, 기준"),
    ("impact", "명. 영향, 충격 / 동. 영향을 주다"),
    ("obtain", "동. 얻다, 입수하다"),
    ("ignore", "동. 무시하다"),
    ("affordable", "형. 감당할 수 있는, 적절한"),
    ("tolerate", "동. 용인하다, 참다, 견디다"),
    ("designated", "형. 지정된"),
    ("grateful", "형. 고마워하는, 감사하는"),
    ("skilled", "형. 숙련된, 노련한"),
    # 숙어 및 관용 표현 (5개)
    ("confirm one's reservation", "예약을 확인하다"),
    ("conduct a poll", "여론조사를 하다"),
    ("be valid for", "~에 유효하다, 타당하다"),
    ("be similar to+명사", "~와 비슷하다"),
    ("be aware that", "~라는 것을 알다"),
]

dat_13 = [
    ("pace", "명. 속도 / 동. 속도를 유지하다, 자기에게 맞는 속도를 찾다"),
    ("dwell", "동. 살다, 거주하다"),
    ("threaten", "동. 협박하다, 위태롭게 하다"),
    ("tight", "형. 단단한, 꽉 조여 있는 / 부. 단단히, 꽉"),
    ("quote", "동. 인용하다, 전달하다"),
    ("ideal", "형. 이상적인, 가장 알맞은 / 명. 이상적인 것[사람]"),
    ("certificate", "명. 증서, 증명서"),
    ("outline", "동. 개요를 서술하다, 윤곽을 보여주다 / 명. 개요, 윤곽"),
    ("distribute", "동. 나누어 주다, 분배하다, 유통시키다"),
    ("mortgage", "명. 대출(금) / 동. 저당 잡히다"),
    ("excessive", "형. 지나친, 과도한"),
    ("organization", "명. 조직, 단체"),
    ("outgrow", "동. 보다 더 커지다, 많아지다"),
    ("inhibit", "동. 억제하다, 저해하다"),
    ("improvise", "동. 즉흥적으로 하다"),
    ("remedy", "명. 처리 방안, 해결책, 치료약 / 동. 개선하다, 교정하다"),
    ("diabetes", "명. 당뇨병"),
    ("high-profile", "형. 세간의 이목을 끄는"),
    ("lingering", "형. 오래 끄는, 오래 가는"),
    ("fair", "형. 타당한, 공정한, 공평한"),
    ("injury", "명. 부상, 상처, 피해"),
    ("bistro", "명. 작은 식당"),
    ("celebrity", "명. 유명 인사"),
    ("hinder", "동. 저해하다, 방해하다"),
    ("impose", "동. 도입하다, 시행하다, 부과하다"),
    # 숙어 및 관용 표현 (5개)
    ("be eligible for", "~에 대한 자격이 있다"),
    ("run short of", "~가 부족하다"),
    ("be equipped with", "~을 갖추다"),
    ("in observance of", "~을 준수하여"),
    ("on purpose", "고의로"),
]

dat_14 = [
    ("regulation", "명. 규정, 규제"),
    ("shorten", "동. 짧게 하다, 단축하다, 짧아지다"),
    ("sort", "명. 종류, 부류, 유형 / 동. 분류하다, 구분하다, 해결하다"),
    ("insurance", "명. 보험"),
    ("intermediate", "형. 중간의, 중급의 / 명. 중급자"),
    ("exotic", "형. 외국의, 이국적인"),
    ("flood", "명. 홍수, 쇄도, 폭주 / 동. 침수되다, 물에 잠기다"),
    ("declaration", "명. 선언, 공표"),
    ("withdraw", "동. 철수하다, 철회하다, 인출하다"),
    ("administrative", "형. 행정상의, 관리상의"),
    ("amicable", "형. 우호적인, 원만한"),
    ("recurring", "형. 되풀이하여 발생하는"),
    ("cosmetic", "명. 화장품 / 형. 성형의"),
    ("prominent", "형. 중요한, 유명한, 눈에 잘 띄는"),
    ("trigger", "명. 방아쇠, 도화선 / 동. 촉발시키다, 작동시키다"),
    ("souvenir", "명. 기념품"),
    ("wire", "명. 철사, 전선 / 동. 연결하다, 송금하다"),
    ("enclosed", "형. 동봉된, 에워싸인"),
    ("amenity", "명. 생활 편의 시설"),
    ("sip", "동. 홀짝이다, 조금씩 마시다"),
    ("wind turbine", "명. 풍력 발전용 터빈"),
    ("boast", "동. 뽐내다, 자랑하다 / 명. 자랑"),
    ("retail", "명. 소매 / 동. 소매하다"),
    ("payroll", "명. 급여 대상자 명단, 급여 지불 총액"),
    ("immaculate", "형. 티 하나 없이 깔끔한, 오류가 전혀 없는"),
    # 숙어 및 관용 표현 (5개)
    ("for your convenience", "편의를 위해서"),
    ("under pressure", "압력 하에, 부담을 가지고"),
    ("with ease", "쉽게"),
    ("apologize for 이유", "~에 대해 사과하다"),
    ("lay off", "해고하다"),
]

dat_15 = [
    ("activate", "동. 작동시키다, 활성화 시키다"),
    ("archive", "명. 기록 보관소 / 동. 기록 보관소에 보관하다"),
    ("generous", "형. 후한, 너그러운"),
    ("compensation", "명. 보상(금), 이득"),
    ("expedite", "동. 더 신속히 처리하다"),
    ("solicit", "동. 간청하다, 요청하다"),
    ("prestigious", "형. 명망 있는, 일류의"),
    ("prolific", "형. 다작하는, 열매를 많이 맺는"),
    ("eligible", "형. ~을 가질 수 있는, 적격의, 적임의, 바람직한"),
    ("attraction", "명. 끌림, 명소, 명물, 매력"),
    ("intermittently", "부. 간헐적으로"),
    ("furnishing", "명. 가구, 비품"),
    ("courtesy", "명. 공손함, 정중함 / 형. 무료의, 서비스의"),
    ("carousel", "명. 수하물 컨베이어 벨트"),
    ("opposite", "형. 건너 편의, 다른 쪽의 / 명. 반대, 반의어"),
    ("launch", "동. 시작하다, 개시하다, 착수하다, 출시하다 / 명. 개시, 출시, 발사"),
    ("trim", "동. 다듬다, 손질하다 / 명. 다듬기, 장식"),
    ("objective", "명. 목표, 목적 / 형. 객관적인, 실재하는"),
    ("assorted", "형. 여러 가지의, 갖은"),
    ("knowledgeable", "형. 아는 것이 많은, 지식 있는, 총명한"),
    ("restriction", "명. 제한, 규제, 제약, 구속"),
    ("authentic", "형. 진짜의, 진품인"),
    ("prepaid", "형. 선불된, 선납된"),
    ("acceptable", "형. 용인되는, 받아들일 수 있는"),
    ("scope", "명. 범위, 기회 / 동. 자세히 살피다"),
    # 숙어 및 관용 표현 (5개)
    ("in response to", "~에 응하여"),
    ("proximity to", "~에의 근접성"),
    ("in duplicate", "2통으로"),
    ("account for", "설명하다, 처리하다"),
    ("be aware of", "~을 알다, 인지하다"),
]

dat_16 = [
    ("rapidly", "부. 빠르게"),
    ("decorative", "형. 장식이 된, 장식용의"),
    ("briefly", "부. 잠시, 간단히"),
    ("talented", "형. 재능이 있는, 재주가 있는"),
    ("perk", "명. (급료 이외의) 특전"),
    ("thermometer", "명. 온도계, 체온계"),
    ("appliance", "명. 기기"),
    ("suit", "명. 정장, 한 세트 / 동. 어울리다, 맞다"),
    ("apologize", "동. 사과하다"),
    ("associated", "형. 관련된"),
    ("enormous", "형. 막대한, 거대한"),
    ("obvious", "형. 분명한, 명백한"),
    ("conceal", "동. 감추다, 숨기다"),
    ("dietary", "형. 규정식의, 식이 요법의 / 명. 규정량"),
    ("preference", "명. 선호, 애호"),
    ("ornament", "명. 장신구, 장식품"),
    ("down payment", "명. (할부금의) 착수금, 계약금"),
    ("devastate", "동. 완전히 파괴하다, 엄청난 충격을 주다"),
    ("enactment", "명. 법률 제정, 입법"),
    ("convene", "동. 소집하다, 회합하다"),
    ("clearance", "명. (불필요한 것) 없애기, 정리"),
    ("retreat", "동. 후퇴하다, 철수하다 / 명. 후퇴, 철수, 퇴각"),
    ("expense", "명. 돈, 비용"),
    ("closely", "부. 밀접하게, 면밀히"),
    ("handle", "동. 다루다, 처리하다 / 명. 손잡이"),
    # 숙어 및 관용 표현 (5개)
    ("put emphasis on", "~을 강조하다"),
    ("be sufficient in supply", "공급 물량이 넉넉하다"),
    ("pending decision", "미결 문제"),
    ("dramatically increase", "극적으로 증가하다"),
    ("gradually decline", "점차로 저하하다, 하락하다"),
]

dat_17 = [
    ("crate", "명. (물품 운송용 대형 나무) 상자"),
    ("vegetarian", "명. 채식주의자"),
    ("majority", "명. 다수, 가장 많은 수"),
    ("faithful", "형. 충실한, 충직한"),
    ("negotiate", "동. 협상하다, 교섭하다, 타결하다"),
    ("exactly", "부. 정확히, 꼭, 틀림없이"),
    ("heavily", "부. (양이나 정도가) 심하게, 아주 많이"),
    ("symbolize", "동. 상징하다"),
    ("strictly", "부. 엄격히, 엄하게, 절대적으로"),
    ("functional", "형. 기능 위주의, 실용적인"),
    ("inventory", "명. 물품 목록, 재고(품) / 동. ~의 목록을 만들다"),
    ("productivity", "명. 생산성"),
    ("restore", "동. 회복시키다, 복원[복구]하다"),
    ("sacrifice", "명. 희생, 희생물, 제물"),
    ("exclusive", "형. 독점적인, 전용의 / 명. 독점 기사"),
    ("approval", "명. 인정, 찬성, 승인"),
    ("identify", "동. 확인하다, 찾다, 알아보게 하다"),
    ("recognition", "명. 인식, 인정, 승인, 표창"),
    ("friendly", "형. 친절한, 우호적인, 상냥한"),
    ("risk", "명. 위험, 위험 요소 / 동. 위태롭게 하다"),
    ("authorization", "명. 허가, 인가, 허가(증)"),
    ("patient", "명. 환자 / 형. 참을성 있는, 인내심 있는"),
    ("intend", "동. 의도하다, 작정하다"),
    ("include", "동. 포함하다"),
    ("previous", "형. 이전의, 바로 앞의"),
    # 숙어 및 관용 표현 (5개)
    ("collaborate on", "~에 대해 협동하다"),
    ("depend on", "~에 의존하다"),
    ("lead to", "~로 이어지다"),
    ("inform, notify, remind A of B", "A에게 B에 대해서 알리다"),
    ("name A to B", "A를 B로 임명하다"),
]

dat_18 = [
    ("release", "동. 풀어 주다, 석방[해방]하다 / 명. 석방, 발표[공개], 개봉"),
    ("circulate", "동. 순환하다, 유포하다"),
    ("drawing", "명. 그림, 스케치, 제비뽑기, 추첨"),
    ("controversy", "명. 논란"),
    ("evidence", "명. 증거, 흔적"),
    ("biodegradable", "형. 생분해성의"),
    ("asset", "명. 자산, 재산"),
    ("specific", "형. 구체적인, 명확한, 특정한"),
    ("relative", "형. 비교상의, 상대적인 / 명. 친척, 동족"),
    ("garage", "명. 차고, 주차장 / 동. 차고에 넣다"),
    ("cabin", "명. (배의) 객실, 선실, (항공기의) 선실, 오두막집"),
    ("selection", "명. 선발, 선정, 선택"),
    ("install", "동. 설비하다, 설치하다"),
    ("reduction", "명. 축소, 삭감, 감소, 인하"),
    ("range", "명. 범위, 다양성 / 동. A에서 B까지 다양하다, 포괄하다"),
    ("despite", "전. ~에도 불구하고"),
    ("among", "전. ~에 둘러싸인, ~의 가운데, 사이에"),
    ("proudly", "부. 자랑스럽게"),
    ("near", "형. 가까운 / 부. 가까이 / 전. (거리상, 시간상) 에서 가까이"),
    ("solid", "형. 단단한, 고체의, 견고한 / 명. 고체"),
    ("statue", "명. 조각상"),
    ("transmit", "동. 전송하다, 전도하다"),
    ("prolong", "동. 연장시키다, 연장하다"),
    ("abolish", "동. (법률, 제도, 조직 등을) 폐지하다"),
    ("committed", "형. 헌신적인, 열성적인"),
    # 숙어 및 관용 표현 (5개)
    ("take A into consideration", "A를 고려하다"),
    ("be aimed at", "~을 목표로 삼다"),
    ("last-minute change", "막바지 변경"),
    ("extensive knowledge", "해박한 지식"),
    ("confidential document", "기밀 서류"),
]

dat_19 = [
    ("entitle", "동. 자격을 주다, 권리를 주다"),
    ("fierce", "형. 격렬한, 맹렬한, 극심한"),
    ("mark", "동. 표시하다, 기념[축하]하다 / 명. 자국[흔적], 표시"),
    ("solidify", "동. 굳어지다, 확고해지다"),
    ("inspection", "명. 점검, 검사, 검토"),
    ("interfere", "동. 간섭하다, 개입하다, 참견하다"),
    ("proceed", "동. 진행하다, 계속해서 ~을 하다"),
    ("prohibit", "동. 금지하다, 하지 못하게 하다"),
    ("offering", "명. 제공된 것, 제물"),
    ("arguably", "부. 주장하건대, 거의 틀림없이"),
    ("distribution", "명. 분배, 분포, 배부, 배급"),
    ("scenic", "형. 경치가 좋은"),
    ("reluctant", "형. 꺼리는, 마지못한, 주저하는"),
    ("skeptical", "형. 회의적인, 의심 많은"),
    ("subtle", "형. 미묘한, 교묘한, 절묘한"),
    ("intensity", "명. 강렬함, 격렬함, 강도"),
    ("duration", "명. 지속, (지속되는) 기간"),
    ("interval", "명. 간격, 중간 휴식 시간"),
    ("frequency", "명. 빈도, 잦음, 주파수"),
    ("primary", "형. 주된, 주요한, 최초의"),
    ("prior", "형. 사전의, 우선하는"),
    ("acquire", "동. 습득하다, 얻다, 획득하다"),
    ("potential", "형. 가능성이 있는, 잠재적인 / 명. 가능성, 잠재력"),
    ("estimate", "명. 추정, 견적서 / 동. 추산[추정]하다"),
    ("circumstance", "명. 환경, 상황, 형편[사정]"),
    # 숙어 및 관용 표현 (5개)
    ("distinguished professor", "저명한 교수"),
    ("demanding supervisor", "까다로운 상사"),
    ("have technical problems", "기술적인 문제가 있다"),
    ("as mentioned earlier", "앞서 말한 바와 같이"),
    ("be filled with", "~로 가득차다"),
]

dat_20 = [
    ("generate", "동. 발생시키다, 만들어 내다"),
    ("anticipate", "동. 예상하다, 예측하다, 기대하다"),
    ("adequate", "형. 충분한, 적절한"),
    ("predict", "동. 예측[예견]하다"),
    ("arbitrary", "형. 임의적인, 제멋대로인, 독단적인"),
    ("advocate", "동. 지지하다, 옹호하다 / 명. 옹호자, 지지자, 변호사"),
    ("mandatory", "형. 법에 정해진, 의무적인"),
    ("mute", "형. 무언의, 말없는"),
    ("ample", "형. 충분한, 풍만한"),
    ("assess", "동. 재다, 평가하다"),
    ("judge", "명. 판사, 심판, 심사위원 / 동. 판단하다, 추정하다"),
    ("appearance", "명. (겉)모습, 외모, 출현"),
    ("ordinary", "형. 보통의, 일상적인, 평범한"),
    ("physical", "형. 육체[신체]의, 물질의 / 명. 신체검사, 건강 진단"),
    ("lengthy", "형. 너무 긴, 장황한, 지루한"),
    ("essential", "형. 필수적인, 본질[근본]적인 / 명. 필수적인 것, 핵심 사항, 요점"),
    ("disease", "명. 질병, 질환"),
    ("agriculture", "명. 농업"),
    ("confusion", "명. 혼란, 혼동, 당혹"),
    ("rash", "명. 발진, 다발, 빈발 / 형. 경솔한, 성급한"),
    ("registration", "명. 등록"),
    ("strategy", "명. 계획, 전략"),
    ("enhance", "동. 강화하다, 향상시키다"),
    ("constant", "형. 끊임없는, 거듭되는, 변함없는"),
    ("encounter", "동. 맞닥뜨리다 / 명. 만남, 조우, 접촉"),
    # 숙어 및 관용 표현 (5개)
    ("close a deal", "계약을 체결하다, 거래를 매듭짓다"),
    ("miss a deadline", "기한을 놓치다"),
    ("attract qualified applicants", "자격을 갖춘 지원자를 유치하다"),
    ("for a limited time only", "한정된 기간 동안만"),
    ("on installment", "할부로"),
]

dat_21 = [
    ("manipulate", "동. 조종하다, 다루다, 조작하다"),
    ("foster", "동. 조성하다, 발전시키다, 위탁 양육하다"),
    ("eliminate", "동. 제거하다, 삭제하다"),
    ("eradicate", "동. 근절하다, 뿌리뽑다"),
    ("extensive", "형. 광범위한, 아주 넓은"),
    ("diner", "명. 식사하는 손님"),
    ("turnout", "명. 참가자의 수, 투표자의 수"),
    ("adjourn", "동. 휴정하다, 휴회하다"),
    ("entire", "형. 전체의, 온"),
    ("narrow", "형. 좁은, 아슬아슬하게"),
    ("broad", "형. 넓은"),
    ("apprehensive", "형. 걱정되는, 불안한"),
    ("commensurate", "형. 어울리는, 상응하는"),
    ("prevalent", "형. 일반적인, 널리 퍼져 있는"),
    ("contemporary", "형. 동시대의, 당대의, 현대의 / 명. 동년배"),
    ("dull", "형. 따분한, 흐릿한, 칙칙한 / 명. 둔해지다, 약해지다"),
    ("alleviate", "동. 완화하다"),
    ("tedious", "형. 지루한, 싫증나는"),
    ("outdated", "형. 구식인"),
    ("sharp", "형. 날카로운, 급격한 / 부. (특정 시간 표현 뒤)정각"),
    ("reinforce", "동. 강화하다, 보강하다"),
    ("ramp", "명. 경사로"),
    ("employ", "동. 고용하다, 쓰다"),
    ("correctly", "부. 똑바로, 바르게"),
    ("engagement", "명. 약혼, 업무"),
    # 숙어 및 관용 표현 (5개)
    ("boost sales", "매출을 증대시키다"),
    ("establish a partnership", "파트너쉽을 구축하다"),
    ("allocate budget", "예산을 할당하다"),
    ("monitor financial performance", "재무 성과를 모니터링하다"),
    ("resolve conflicts", "갈등을 해결하다"),
]

dat_22 = [
    ("identical", "형. 동일한, 똑같은"),
    ("definitely", "부. 확실히, 분명히"),
    ("historically", "부. 역사적으로"),
    ("periodically", "부. 주기적으로"),
    ("missing", "형. 없어진, 분실된"),
    ("scaffolding", "명. (건축 공사장의) 비계"),
    ("respectfully", "부. 정중하게"),
    ("policy", "명. 정책, 방침"),
    ("contact", "명. 연락, 접촉"),
    ("remain", "동. 계속 ~이다, 남다"),
    ("sustain", "동. 계속시키다, 지속시키다"),
    ("weekday", "명. 평일"),
    ("follow", "동. 준수하다, 따라가다"),
    ("portrait", "명. 초상화, 묘사"),
    ("accountable", "형. 책임이 있는"),
    ("vegetable", "명. 채소, 야채"),
    ("harbor", "명. 항구, 항만, 피난처"),
    ("coordinate", "동. 조직화하다, 조정하다 / 명. 좌표, 함께 잘 어울리는 옷들"),
    ("motivate", "동. 동기를 부여하다"),
    ("found", "동. 설립하다, 세우다"),
    ("amend", "동. 개정하다, 수정하다"),
    ("validate", "동. 입증하다, 승인[인정]하다"),
    ("ventilation", "명. 환기, 통풍"),
    ("contaminate", "동. 오염시키다"),
    ("deplete", "동. 대폭 감소시키다, 격감시키다"),
    # 숙어 및 관용 표현 (5개)
    ("sustainable practices", "지속가능한 관행"),
    ("expand product lines", "제품 라인을 확장하다"),
    ("maximize profits", "수익을 극대화하다"),
    ("target specific demographics", "특정 인구 통계를 타겟으로 하다"),
    ("reliable service", "신뢰할 만한 서비스"),
]

dat_23 = [
    ("pesticide", "명. 살충제, 농약"),
    ("emission", "명. 배출, 배기가스"),
    ("synthetic", "형. 합성한, 인조의 / 명. 합성 물질"),
    ("artificial", "형. 인공의, 인위적인"),
    ("adopt", "동. 입양하다, 채택하다"),
    ("anonymous", "형. 익명인, 익명으로 된"),
    ("ambiguous", "형. 애매모호한, 애매한"),
    ("allocation", "명. 할당량, 할당"),
    ("acknowledge", "동. 인정하다, 받았음을 알리다"),
    ("deep", "형. 깊은, (삭감, 할인 등) 대폭적인"),
    ("responsible", "형. 책임이 있는"),
    ("transaction", "명. 거래, 매매, 처리 (과정)"),
    ("gladly", "부. 기꺼이, 기쁘게"),
    ("draft", "명. 원고, 초안"),
    ("finalize", "동. 마무리짓다, 완결하다"),
    ("tenant", "명. 세입자, 임차인 / 동. 임차해서[세 들어] 살다"),
    ("raise", "동. 들어올리다, (자금, 사람 등) 모으다"),
    ("adapt", "동. 맞추다, 조정하다, 적응하다, 각색하다"),
    ("following", "형. 그 다음의 / 전. ~후에, ~에 따라 / 명. 추종자[팬]들"),
    ("cathedral", "명. 대성당"),
    ("ambitious", "형. 야심 있는, 어마어마한"),
    ("outlet", "명. 직판점, 할인점, 콘센트"),
    ("investment", "명. 투자, 투자액"),
    ("banquet", "명. 연회, 만찬"),
    ("outstanding", "형. 뛰어난, 걸출한, 두드러진, 미지불된"),
    # 숙어 및 관용 표현 (5개)
    ("valuable feedback", "귀중한 피드백"),
    ("comply with industry standards", "업계 표준을 준수하다"),
    ("call off a meeting", "회의를 취소하다"),
    ("run a company", "회사를 운영하다"),
    ("set up a business", "사업을 시작하다"),
]

dat_24 = [
    ("weigh", "동. 무게를 달다, 저울질하다"),
    ("scale", "명. 규모, 범위, 등급 / 동. 오르다"),
    ("terms", "명. (합의, 계약 등의) 조건"),
    ("regarding", "전. ~에 관하여, 대하여"),
    ("including", "전. ~을 포함하여"),
    ("integrate", "동. 통합시키다"),
    ("seating", "명. 좌석, 자리"),
    ("faulty", "형. 결함이 있는, 잘못된"),
    ("possibly", "부. 아마"),
    ("await", "동. 기다리다"),
    ("advisable", "형. 바람직한, 권할 만한"),
    ("sophisticated", "형. 세련된, 교양 있는, 정교한"),
    ("instant", "형. 즉각적인 / 명. 순간, 아주 짧은 동안"),
    ("appreciate", "동. 진가를 알아보다, 인정하다, 인식하다"),
    ("describe", "동. 말하다, 묘사하다"),
    ("superfluous", "형. 필요치 않은, 불필요한"),
    ("shred", "동. 자르다, 찢다, 채를 썰다 / 명. 조각, 티끌"),
    ("nominee", "명. 지명된 사람, 후보"),
    ("spare", "형. 남는, 여분의 / 동. 할애하다"),
    ("aim", "명. 목적, 목표 / 동. 목표하다"),
    ("hustle", "동. 떠밀다, 재촉하다"),
    ("contributor", "명. 기고자, 토론자, 기부자, 기여자"),
    ("deal", "동. 처리하다(with) / 명. 거래, 정책"),
    ("behalf", "명. 이익, 원조, 자기편, 지지"),
    ("lack", "명. 부족, 결핍 / 동. ~이 없다, 부족하다"),
    # 숙어 및 관용 표현 (5개)
    ("accurately measure", "정확하게 측정하다"),
    ("regularly updated", "정기적으로 업데이트하다"),
    ("precisely calculate", "정밀하게 계산하다"),
    ("easily accessible", "쉽게 접근 가능한"),
    ("widely recognized", "널리 인정받는"),
]

dat_25 = [
    ("description", "명. 서술, 기술, 묘사"),
    ("statement", "명. 성명(서), 진술(서)"),
    ("compliance", "명. 준수, 따름"),
    ("detailed", "형. 상세한"),
    ("recent", "형. 최근의"),
    ("expertise", "명. 전문 지식"),
    ("reputation", "명. 평판, 명성"),
    ("value", "명. 가치 / 동. 소중하게 생각하다, 평가하다"),
    ("loyalty", "명. 충실, 충성"),
    ("reference", "명. 말하기, 언급, 참고"),
    ("arrange", "동. 마련하다, 정리하다, 배열하다"),
    ("warranty", "명. 품질 보증서"),
    ("independent", "형. 독립된, 독립적인"),
    ("surplus", "명. 과잉, 흑자 / 형. 과잉의, 잉여의"),
    ("obstruct", "동. 막다, 방해하다"),
    ("assign", "동. 맡기다, 배정하다, 부과하다"),
    ("assure", "동. 장담하다, 확언하다"),
    ("address", "명. 주소 / 동. 주소를 쓰다, 연설하다, 해결하다"),
    ("effort", "명. 수고, 노력"),
    ("questionnaire", "명. 설문지"),
    ("regain", "동. 되찾다, 회복하다"),
    ("fulfill", "동. 성취하다, 실현하다, 이행하다"),
    ("subscription", "명. 구독료, 구독, 기부(금)"),
    ("process", "명. 과정, 절차"),
    ("coverage", "명. 보도, 범위"),
    # 숙어 및 관용 표현 (5개)
    ("incredibly versatile", "놀라울 정도로 다재다능한"),
    ("unanimously agree", "만장일치로 동의하다"),
    ("adjust accordingly", "그에 따라 조정하다"),
    ("actively participate in", "적극적으로 참여하다"),
    ("professionally develop", "전문적으로 개발하다"),
]

dat_26 = [
    ("remind", "동. 상기시키다, 다시 한 번 알려주다"),
    ("obligation", "명. 의무"),
    ("revoke", "동. 폐지하다, 철회, 취소하다"),
    ("sensitive", "형. 세심한, 예민한"),
    ("perceive", "동. 감지하다, 인지하다"),
    ("descend", "동. 내려오다, 경사지다, 내리막이 되다"),
    ("modest", "형. (크기, 가격, 중요성 등이) 보통의, 겸손한, 수수한"),
    ("adjust", "동. 조정하다, 바로잡다"),
    ("appealing", "형. 매력적인, 호소하는, 애원하는"),
    ("sizable", "형. 상당한 크기의, 꽤 큰"),
    ("tie", "동. 묶다, 달다 / 명. 넥타이, 끈"),
    ("steep", "형. 가파른, 급격한, 너무 비싼"),
    ("subsequent", "형. 그 다음의, 차후의"),
    ("numerous", "형. 많은"),
    ("conserve", "동. 아끼다, 보존하다"),
    ("outgoing", "형. 외향적인, 사교적인"),
    ("status", "명. 신분, 지위"),
    ("profitable", "형. 수익성이 있는, 이득이 되는, 유익한"),
    ("expect", "동. 예상하다, 기대하다"),
    ("different", "형. 다른, 차이가 나는"),
    ("temperature", "명. 온도, 기온, 체온"),
    ("orderly", "형. 정돈된, 정연한, 질서 있는"),
    ("leisurely", "형. 한가한, 여유로운, 느긋한"),
    ("delicate", "형. 연약한, 여린, 다치기 쉬운, 섬세한"),
    ("growth", "명. 성장, 증가"),
    # 숙어 및 관용 표현 (5개)
    ("immediately after", "곧, 곧 뒤따라"),
    ("receive a discount on", "에 할인을 받다"),
    ("heavy rain, snow", "폭우, 폭설"),
    ("additional fees, costs", "추가 요금, 비용"),
    ("be closely related to", "와 밀접하게 관련이 있다"),
]

dat_27 = [
    ("intentional", "형. 의도적인, 고의로 한"),
    ("enlist", "동. 요청하다, 징집하다"),
    ("articulate", "동. 분명히 표현하다, 설명하다 / 형. 또렷한, 분명히 표현하는"),
    ("unprecedented", "형. 전례 없는"),
    ("patronage", "명. 후원, 지원"),
    ("establish", "동. 설립하다, 수립하다, 확고히 하다"),
    ("affluent", "형. 부유한"),
    ("automatically", "부. 자동으로"),
    ("populate", "동. 살다, 거주하다, 이주시키다"),
    ("adverse", "형. 부정적인, 불리한"),
    ("understaffed", "형. 인원이 부족한"),
    ("halt", "동. 멈추다, 세우다 / 명. 멈춤, 중단"),
    ("routine", "명. 루틴, 일상 / 형. 일상적인, 보통의"),
    ("approach", "동. 다가가다, 접촉하다 / 명. 접근법, 다가감"),
    ("rather", "부. 꽤, 약간, 상당히"),
    ("elect", "동. 선출하다, 선택하다 / 형. 당선된"),
    ("broadcast", "동. 방송하다, 널리 알리다 / 명. 방송"),
    ("ahead", "부. 앞으로, 앞에, 미리"),
    ("otherwise", "부. 그렇지 않으면"),
    ("allege", "동. 혐의를 제기하다, 주장하다"),
    ("fluent", "형. 유창한, 능숙한"),
    ("consume", "동. 소모하다, 소비하다"),
    ("marginal", "형. 미미한, 중요하지 않은, 주변부의"),
    ("industrial", "형. 산업의, 공업의"),
    ("comparable", "형. 비슷한, 비교할 만한"),
    # 숙어 및 관용 표현 (5개)
    ("widely available", "널리 이용되는"),
    ("tight regulations, rules", "강경한 규제, 규칙"),
    ("specialize in", "~을 전문으로 하다"),
    ("be designed for", "을 위해 고안되다"),
    ("be on vacation", "휴가 중이다"),
]

dat_28 = [
    ("successive", "형. 연속적인, 연이은, 잇따른"),
    ("responsive", "형. 즉각 반응하는, 호응하는"),
    ("entry", "명. 입장, 출입, 가입"),
    ("produce", "동. 생산하다 / 명. 농작물, 농산물"),
    ("grant", "동. 승인하다, 인정하다 / 명. 보조금"),
    ("retain", "동. 유지하다, 간직하다"),
    ("mature", "형. 어른스러운, 분별 있는 / 동. 어른스러워지다, 성숙해지다"),
    ("delete", "동. 삭제하다"),
    ("remark", "명. 발언, 언급, 주목"),
    ("overstate", "동. 과장하다"),
    ("impulsive", "형. 충동적인"),
    ("impartial", "형. 공정한"),
    ("scheme", "명. 계획, 제도 / 동. 책략을 꾸미다"),
    ("ethic", "명. 윤리, 도덕"),
    ("instrumental", "형. 중요한, 악기에 의한 / 명. 기악곡"),
    ("harsh", "형. 가혹한, 냉혹한, 혹독한"),
    ("costly", "형. 많은 돈이 드는"),
    ("merchant", "명. 상인"),
    ("audiovisual", "형. 시청각의"),
    ("edible", "형. 먹을 수 있는, 식용의"),
    ("risky", "형. 위험한"),
    ("discard", "동. 버리다, 폐기하다 / 명. 버린 패"),
    ("rigid", "형. 엄격한, 융통성 없는"),
    ("enroll", "동. 등록하다, 입학하다"),
    ("rewarding", "형. 보람 있는, 돈을 많이 버는"),
    # 숙어 및 관용 표현 (5개)
    ("in a minute", "즉각, 당장"),
    ("in particular", "특히, 특별히"),
    ("under control", "통제되는, 지배되는"),
    ("raise awareness of", "~에 대한 인식을 고취하다"),
    ("take the opportunity", "기회를 잡다"),
]

dat_29 = [
    ("debate", "명. 토론, 논쟁 / 동. 논의하다, 숙고하다"),
    ("surpass", "동. 능가하다, 뛰어넘다"),
    ("insert", "동. 끼우다, 삽입하다 / 명. 삽입 광고, 부속품"),
    ("tricky", "형. 힘든, 까다로운, 교묘한"),
    ("dozen", "명. 12개 짜리 한 묶음, 다스"),
    ("march", "동. 행진하다 / 명. 행군, 행진"),
    ("withstand", "동. 견뎌 내다, 이겨 내다"),
    ("offset", "동. 상쇄하다, 벌충하다"),
    ("revenue", "명. 수익, 수입"),
    ("retention", "명. 보유, 유지, 정체, 잔류"),
    ("consolidate", "동. 굳히다, 강화하다, 통합하다"),
    ("diagnosis", "명. 진단"),
    ("punish", "동. 처벌하다, 벌주다"),
    ("culminate", "동. 막을 내리다, 끝이 나다"),
    ("attorney", "명. 변호사"),
    ("fabric", "명. 직물, 천"),
    ("savvy", "명. 지식, 상식, 요령"),
    ("barter", "동. 물물교환하다"),
    ("catastrophe", "명. 참사, 재앙"),
    ("abandon", "동. 버리다, 유기하다"),
    ("decompose", "동. 분해되다, 부패되다"),
    ("resource", "명. 자원, 재원 / 동. 자원을 제공하다"),
    ("means", "명. 수단, 방법, 돈, 재력"),
    ("persuade", "동. 설득하다"),
    ("solely", "부. 오로지, 단지, 단독으로"),
    # 숙어 및 관용 표현 (5개)
    ("follow up on", "~에 대해 후속 조치를 취하다"),
    ("have yet to do", "아직 ~하지 않았다"),
    ("by the way", "그런데, 한편"),
    ("hold a festival", "축제를 개최하다"),
    ("take place", "발생하다"),
]

dat_30 = [
    ("flair", "명. 재능, 재주, 솜씨"),
    ("reap", "동. 거두다, 수확하다, 거둬들이다"),
    ("accumulate", "동. 모으다, 축적하다"),
    ("fleet", "명. 함대"),
    ("obscure", "형. 무명의, 이해하기 힘든, 모호한 / 동. 이해하기 어렵게 하다"),
    ("manifest", "동. 나타내다, 분명해지다 / 형. 분명한"),
    ("entail", "동. 수반하다"),
    ("staple", "형. 주된, 주요한"),
    ("furnished", "형. 가구가 비치된"),
    ("serving", "명. (음식의) 1인분"),
    ("scarcity", "명. 부족, 결핍"),
    ("transferable", "형. 이동 가능한, 양도 가능한"),
    ("mundane", "형. 재미 없는, 일상적인"),
    ("elaborate", "형. 정교한, 정성을 들인 / 동. 자세히 말하다, 정교하게 만들어 내다"),
    ("conceive", "동. 마음속으로 하다, 상상하다"),
    ("deficit", "명. 적자, 부족액, 결손"),
    ("monetary", "형. 통화의, 화폐의"),
    ("energetic", "형. 활동적인"),
    ("vibrant", "형. 활기찬, 강렬한, 힘찬"),
    ("proliferation", "명. 급증, 확산"),
    ("savory", "형. 맛 좋은, 향긋한, 즐거운"),
    ("fluctuate", "동. 등락을 거듭하다"),
    ("probable", "형. 있을 것 같은, 개연성 있는"),
    ("breakthrough", "명. 돌파구"),
    ("surge", "동. 급등하다, 급증하다 / 명. 급증, 급등, 솟아오름"),
    # 숙어 및 관용 표현 (5개)
    ("rise through the roof", "치솟다"),
    ("figure out", "이해하다"),
    ("give it a thought", "생각해보다"),
    ("up and running", "작동중인"),
    ("cut down on", "~을 줄이다"),
]
